### ISSUE TITLE
TypeError: RetailCRM is not a constructor

### ISSUE THREAD

**Issue by iMiF** [Omashu/node-retailcrm-api#2]
Привет!
При попытке запустить пример из readme (https://www.npmjs.com/package/node-retailcrm-api) возникает ошибка: _TypeError: RetailCRM is not a constructor_

Похожую проблему нашел тут: https://github.com/panva/node-openid-client/issues/75 но с предлагаемым решением не разобрался. 

Я что-то делаю не так?

**Comment by bump44** [comment]
Привет.
Вероятно сейчас вы можете сделать это так:
```javascript
const RetailCRM = require('node-retailcrm-api').default;

const Client = new RetailCRM.Client({});
```

или вот так:
```javascript
import RetailCRM from 'node-retailcrm-api';

const Client = new RetailCRM.Client({});
```

обратите внимание что модуль возвращает объект, с классом клиента и доступными версиями.

Сейчас я обновил код и теперь модуль экспортируется немного иначе, возможно это решит проблему (вы можете обновиться до последней версии, переустановив пакет), если ничего не помогло, то пожалуйста приложите свой код
